string(MAKE_C_IDENTIFIER ${CLAP_WRAPPER_OUTPUT_NAME} pluginname)
add_library(${pluginname}_as_auv2 MODULE)
target_add_auv2_wrapper(
	TARGET ${pluginname}_as_auv2
	OUTPUT_NAME "${CLAP_WRAPPER_OUTPUT_NAME}"
	BUNDLE_IDENTIFIER "${CLAP_WRAPPER_BUNDLE_IDENTIFIER}"
	BUNDLE_VERSION "${CLAP_WRAPPER_BUNDLE_VERSION}"
	INSTRUMENT_TYPE "${CLAP_WRAPPER_AUV2_INSTRUMENT_TYPE}"
	MANUFACTURER_NAME "DM"
	MANUFACTURER_CODE "dmAd"
	SUBTYPE_CODE "${CLAP_WRAPPER_AUV2_SUBTYPE}"
	MACOSX_EMBEDDED_CLAP_LOCATION "${CLAP_WRAPPER_CLAP_LOCATION}"
)