[package]
name = "dm_rat"
version = "0.1.0"
authors = ["davemollen <davemollen@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2 = "0.6.0"
rat = { path = "../rat" }

[lib]
crate-type = ["cdylib"]